config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/questions', to: 'pages#create_question', as: 'create_question'
  post 'create_vote', to: 'pages#create_vote', as: 'create_vote'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :votes, dependent: :destroy
  before_validation :strip_answers_text
  validates :title, presence: true
  validates :answers_text, presence: true
  validates :title, format: { with: /\bpizza\b/i, message: "must include the word 'pizza'" }

  def voted_by_ip?(ip_address)
    votes.exists?(voter_ip: ip_address)
  end

  def my_answer(ip_address, answer)
    if votes
      vote = votes.find_by(voter_ip: ip_address)
      if vote && vote.answer == answer
        true
      end
    end
  end

  def strip_answers_text
    self.answers_text = self.answers_text.sub(/\A• /, '')
  end

  def count_votes_for(answer)
    num_of_votes = votes.where(answer: answer).count
    num_of_votes == 1 ? "1 vote" : "#{num_of_votes} votes"
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :question

  validates :answer, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @question = Question.new
    @questions = Question.eager_load(:votes).order(created_at: :desc)
    @vote = Vote.new
  end

  def create_question
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path
      flash[:notice] = "Question was recorded successfully!"
    else
      redirect_to root_path
      flash[:alert] = @question.errors.full_messages.join(', ')
    end
  end

  def create_vote
    @question = Question.find(params[:vote][:question_id])
    @vote = Vote.new(vote_params)
    if @question.voted_by_ip?(request.remote_ip)
      redirect_to root_path
      flash[:alert] = "You already voted for this question!"
    else
      if @vote.save
        redirect_to root_path, notice: 'Vote was successfully created.'
      else
        redirect_to root_path
        flash[:alert] = "You must select an answer!"
      end
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :answers_text)
  end

  def vote_params
    params.require(:vote).permit(:question_id, :answer, :voter_ip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzzaPoll</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.13.0/dist/umd/popper.min.js" integrity="sha384-V7EAK4b/js/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container py-4">
  <%# Flashes %>
  <% if flash[:notice].present? %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert].present? %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert] %>
    </div>
  <% end %>
  <%# Add question %>
  <div class="row">
    <div class="col-lg-6 position-static">
      <h4 class="p-3 bg-white fw-bolder">Create a question</h4>
      <div class="bg-light p-4 mb-3">
        <%= simple_form_for @question, url: create_question_path do |f| %>
          <%= f.input :title,
            label: "Your question",
            placeholder: "eg. What is your favourite pizza?" %>
          <%= f.input :answers_text,
            label: "Add possible answers",
            hint: "Hit enter for each answer you want to add",
            input_html: {style:"height: 10rem;", value: "• "},
            placeholder: "tip: Hit enter for each answer you want to add" %>
          <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <%# Vote %>
    <div class="col-lg-6">
      <h4 class="p-3 bg-white fw-bolder">Most recent questions</h4>
      <% if @questions.present? %>
        <% @questions.each do |question| %>
          <div class="bg-light p-4 mb-4">
            <%= simple_form_for @vote, url: create_vote_path do |f| %>
              <%= f.hidden_field :question_id, value: question.id %>
              <div class="">
                <p class=""><%= question.title %></p>
                <% if question.voted_by_ip?(request.remote_ip) %>
                  <p class="text-success"><small>✓ You voted for this question</small></p>
                <% end %>
              </div>
              <% question.answers_text.split(/\n/).each do |answer| %>
                <% if answer != "• " %>
                  <div class="mb-3 w-100 bg-white p-3">
                    <div class="d-flex justify-content-between align-items-center">
                      <p class="m-0">
                        <%= f.radio_button :answer,
                          answer,
                          disabled: (question.my_answer(request.remote_ip, answer)) %>
                          <%= answer.sub(/\A• /, '') %>
                      </p>
                      <p class="m-0 text-nowrap">
                        <%= question.count_votes_for(answer) %>
                      </p>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <%= f.hidden_field :voter_ip, value: request.remote_ip %>
              <p class="m-0"><%= f.button :submit, "Vote",
                class:"btn mt-2 btn-outline-primary" %></p>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <p class="bg-light p-4">No questions yet. Be the first to create one!</p>
      <% end %>
    </div>
  </div>
</div>